{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "financial-service.fullname" . }}
{{- with .Values.secret.values }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}